---

- name: basic packages
  apt:
    pkg:
      - acl
      - htop
      - nginx
      - certbot
      - python-certbot-nginx
      - imagemagick
    state: present
    force: "yes"
    update_cache: "yes"
  become: true

- name: Check that the grapevine config exists
  stat:
    path: /etc/grapevine.config.exs
  register: grapevine_config

- name: copy grapevine config
  copy:
    src: grapevine.config.exs
    dest: /etc/grapevine.config.exs
    mode: 0644
  when: not grapevine_config.stat.exists
  become: yes

- name: make grapevine directory
  file:
    dest: /home/deploy/grapevine
    state: directory
  become: yes
  become_user: deploy

- name: Check that the nginx config exists
  stat:
    path: /etc/nginx/sites-enabled/grapevine
  register: nginx_config

- name: copy nginx config
  copy:
    src: nginx.conf
    dest: /etc/nginx/sites-enabled/grapevine
    mode: 0644
  when: not nginx_config.stat.exists
  become: yes

- name: copy nginx config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: yes

- name: copy systemd file
  copy:
    src: grapevine.service
    dest: /etc/systemd/system/grapevine.service
  become: yes
  notify: reload systemd

- name: enable grapevine service
  systemd:
    name: grapevine.service
    enabled: yes
  become: yes

- name: link the v5 of ncurses.so
  file:
    src: /lib/x86_64-linux-gnu/libncursesw.so.5
    dest: /lib/x86_64-linux-gnu/libncursesw.so.6
    state: link
  become: yes

- name: setup backups folder
  file:
    path: /opt/backups/
    state: directory
  become: yes

- name: copy backup file
  copy:
    src: backup-grapevine.sh
    dest: /opt/
    mode: 0744
  become: yes

- name: Backup the postgres database nightly
  cron:
    name: "pg dump"
    minute: "0"
    hour: "5"
    job: "/opt/backup-grapevine.sh"
  become: yes
