FROM elixir:1.9 as builder
RUN mix local.rebar --force && \
    mix local.hex --force
WORKDIR /app
ENV MIX_ENV=prod
COPY mix.* /app/
RUN mix deps.get --only prod && \
  mix deps.compile

FROM builder as releaser
ENV MIX_ENV=prod
COPY . /app/
RUN mix release && \
  cd _build/prod/rel/telnet/ && \
  tar czf /opt/telnet.tar.gz .
